### ISSUE TITLE
Вывод полного списка задач

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/to_do#13]
Написать функцию, которая выводит полный список задач, отсортированный по датам

**Comment by Napolskiy** [comment]
sortlist = ()
def sortBytasks(my_data):
     if tasks in my_data:
         return sortBytasks[tasks]

def sortBydate(my_data):
    tasks = datetime.data().strftime("%d.%m.%Y")
    return sortBydate(my_data)

print sortlist
