### ISSUE TITLE
Вывод списка задач на сегодня

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/to_do#17]
Добавить на главную страницу вывод списка задач на сегодня

**Comment by DRtishev** [comment]
from flask import Flask, render_template

app = Flask(**name**)

@app.route('/')

def index():
    name = {'nickname' : 'Dimon'}
    dict = {"date" :'bla-bla'}
    return render_template('index.html',title = 'Hello', name = name, dict = dict)

app.run(debug=True)
###########################
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title>{{title}} - project. </title>
    {% else %}
     <title>Мой проект</title>
    {% endif %}
</head>
<body>

<h1>Hello {{name.nickname}} !</h1>

{% for post in dict.date %}

<p>{{post}}</p>

{% endfor %}

</body>
</html>
