### ISSUE TITLE
Ввод описания задачи

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/to_do#2]
Написать функцию, которая запрашивает у пользователя и возвращает описание задачи

**Comment by ViZagorodnia** [comment]
print "Hello"
task = []

def task_description(description):
    task.append([description])
    print task

while True:
    print 'If you want enter new task press - a'
    print 'If you want quite press - q'

```
s = raw_input('what you want? ')
if s == 'q':
    break
elif s == 'a':
    description = str(raw_input('Enter task'))
    task_description(description)
else:
    exit()
```
