### ISSUE TITLE
Форма поиска по дате

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/to_do#21]
Добавить форму ввода даты для поиска задач по ней на главную страницу

**Comment by oleksiitrygubenko** [comment]
from flask import Flask, request
app = Flask(**name**)

@app.route("/")
def enter_date():
    return '<form action="/main" method="GET"><input name="date"><input type="submit" value="Enter date"></form>'

@app.route("/main")
def main():
    return "Events on: " + request.args.get('date')

app.run(debug = True)
